import 'package:flutter/material.dart';

const primaryColor = Color(0xFF5C2CAA);
const primaryShade = Color(0xffCEC0E5);
const infoColor = Color(0xFF1A1825);
const backgroundColor = Colors.white;
const textFieldBorderColor = Color(0xFFBEBBC4);
const hintTextColor = Color(0xffB6B2BC);
const warningTextColor = Color(0xff92400E);
const warningContainerColor = Color(0xffFFF7ED);
const dottedLineColor = Color(0xffD8D6DC);
const hoverColor = Color.fromARGB(60, 241, 233, 255);
const navGradientStartColor = Color(0xFF7D56BB);
const navGradientEndColor = Color(0xFF5C2CAA);
const appBarTextColor = Color(0xff3D3C42);
const searchTextFieldBorderColor = Color(0xffD8D6DC);
const searchTextFieldFillColor = Color(0xffF2F1F3);
const dashboardScaffoldColor = Color(0xffF2F1F3);
const totalSteperColor = Color(0xffB6B2BC);
const stepperInfoColor = Color(0xff3D3C42);
